### ISSUE TITLE
HTTP Grade D and E discriminate searx instances with a custom theme

### ISSUE THREAD

**Issue by unixfox** [dalf/searx-stats2#6]
Giving a lower rating (and probably ranking lower) because a searx instance customized the default theme is actually quite bad.
A few examples that customized the default theme and are apart from that perfectly good Searx instances:
- https://search.stinpriza.org/ - Changed only the logo
- https://suche.elaon.de/ - Changed only the logo
- https://spot.ecloud.global/ - Change the logo and customized the CSS and JS

And I could think of another example that would give a bad rating: minifying on the fly all the assets that aren't minifyied like for example [search_on_category_select.js](https://github.com/asciimoo/searx/blob/master/searx/static/plugins/js/search_on_category_select.js).

Actually the idea of giving grade based on the fact that the HTML files aren't completely the same as the original source code of Searx is a good idea but it's reaching a field where bad and good intentions are mixed together. And it's in this field, using the automated way to distinguish the bad from the good is actually very hard to do.

**Comment by dalf** [comment]
One idea to solve this is to use badges:
 - "Vanilla" : instance with unmodified content from the git repository.
 - "Unique" : instance with unique content.
 - "Approved": "Unique" content but approved (see below)
 - "External": URL to an another host.

Can be extended with:
 - "Google" - google analytics
 - "Matomo"
 - "Fathom"

Then the user can filter by these tags.

"approved" content can be stored in a git repository:
 - either by hash
 - either by URL (with something like wildcard)

Some examples:

File approved.yaml:
```yaml
- hash: ccea4aa40aca2ac30efc6cd85197886e0acc72fc73bb5695bb29ac73a3661616
  approved: true
  privacy-problem: false
  comment: xxxx
- hash: 4d3ada2f3687ff27df2184615e0e3ddb121388c7bac8a52af3bdabd6b4bdce6c
  approved: true
  privacy-problem: false
  comment: xxxx
```

File external.yaml:
```yaml
- url: https://*.cloudflare.com/*
  tags: cloudflare
  privacy-problem: true
- url: https://unpkg.com/*
  tags: cdn
- url: 	https://www.google-analytics.com/*
  tags: google
  privacy-problem: true
```

Then these files are modifed using PR which allow review and moderation.

... and most probably this is an overkill feature.
